### ISSUE TITLE
Unity minigames do not play on github.io

### ISSUE THREAD

**Issue by rmcreyes** [ubclaunchpad/ubcsim2#114]
**Describe the bug**
When playing the game through the app deployed on github.io, Unity minigames do not play.

**Root Cause**
When inspecting the page and observing the console, this log shows up:
![image](https://user-images.githubusercontent.com/31678646/77040225-be6a9400-6974-11ea-851b-ba9fa2eb9a22.png)
I suspect that when deploying the app to GitHub Pages, the new `npm start` script does not run, so the binaries are not fetched, making it impossible to play the minigames.

**To Reproduce**
1. Open the game in https://ubclaunchpad.github.io/ubcsim2/
2. Progress until you trigger a mini game
3. Observe that the mini game does not play

**Expected behavior**
The mini game should be able to play.

**Screenshots**
![image](https://user-images.githubusercontent.com/31678646/77040414-1f926780-6975-11ea-894a-f58cfded781c.png)

**Comment by rmcreyes** [comment]
@cheukyin699 @eloisepeng do we know if `npm run start` is called when deploying master? My suspicion is that `npm run deploy` does not straight up run `npm run start`, but I am not familiar with what exactly the deploy script is doing.

**Comment by cheukyin699** [comment]
`npm run start` is not called when deploying to master. Probably because this would stall the deploy. This is a high priority issue.

I propose that we split the script that starts the app into 2 parts:

1. Download, unpack, and copy the Unity files to their rightful places
2. Actually starting the app (`react-app start`)

Another change that must be made is that we would have to copy the unity files into the build folder itself. Maybe have a script `scripts/deploy.sh` called when you run `npm run deploy` that just builds it and then downloads/unpacks/copies the Unity files to the correct directory.

Another slightly less interesting thing is that we are for some reason making a request to multiple `.ts` files, as shown below:

![image.png](https://images.zenhubusercontent.com/5acc1af04b5806bc2bce66f9/05870518-3f34-4164-a678-299b1e40f066)
